### ISSUE TITLE
Copyright removed

### ISSUE THREAD

**Issue by rjc** [small-utils/xmenu#1]
Hi,

In the last commit you had changed the license from `MIT/X` one to an `MPLv2.0`.

At the same time you had removed all of the copyright notices of the original authors.

The original license clearly states that you're to do whatever you like with the software, as long as you include said copyright notice.

The source files only contain reference to the `LICENSE` file.

It looks like you might be in violation of the original authors' copyright.

Regards,

rjc

**Comment by crocket** [comment]
I'm not a lawyer, but as far as I know, anybody should be able to fork MIT license projects with one that has more strict license.

However, it is probably mistake to remove their names from LICENSE. I'll look for a way to give credits to them.

**Comment by rjc** [comment]
Like I've stated above, one can do whatever they wish with the software as long as they don't claim they're the original author - I specifically mentioned copyright, **not** license, violation.

**Comment by crocket** [comment]
Although I think the commits serve as copyrights according to C4, I added copyrights to README.

**Comment by crocket** [comment]
I just realized that C4 automatically assigns copyrights to commit authors. Thus, I removed copyright from README.

**Comment by rjc** [comment]
I know nothing of `C4` but the commits, which you have mentioned, are only available if ones is to use a repository with all of its history intact. None of that information will be available in a release tarball.

The easiest way to avoid any issues is to retain the current license :^)

Otherwise you may need to copy the old copyright notices, most likely with its old license, into each and every source file which contained the reference to the `LICENSE` file - you can of course keep the refeference as it already points to the new license... but I'm not a lawyer either :^P

**Comment by crocket** [comment]
If you think this project got the copyrights wrong, you could submit a pull request.

I'll merge a pull request anyway if it doesn't look crazy.

**Comment by rjc** [comment]
Copyright is a serious matter and I wouldn't leave it like that as this usually doesn't end well for the fork.

Just my $0.02.

**Comment by crocket** [comment]
Although I could add it back myself, I would like a contributor to add it.
I prefer it that way. I'll wait for some time for a contributor feedback in the form of pull request.

**Comment by crocket** [comment]
I am very new to this copyright business, so I was somewhat careless.
FRIGN, a suckless member, told me it was necessary to have the original copyright information below MPLv2. I'll do that very soon and close this.

**Comment by crocket** [comment]
This one is closed by https://github.com/small-utils/xmenu/commit/d56c0188e8a11b595ae8d844654c60cb96111672
